#!/usr/bin/env bash
#
# Build the hkjn/r Docker image.
#
set -euo pipefail

DOCKER_USER="hkjn"
DOCKER_IMAGE="r"
ARCH="$(uname -m)"

declare -A BASEIMAGES
BASEIMAGES[x86_64]=debian:jesse-slim
BASEIMAGES[armv7l]=hkjn/debian:armv7l

BASEIMAGE=${BASEIMAGES[$ARCH]}
BUILD_DIR="$(mktemp -d)"

sed "s|ARG_FROM|${BASEIMAGE}|g" Dockerfile.in > "$BUILD_DIR/Dockerfile"
TAG="$DOCKER_USER/$DOCKER_IMAGE:$ARCH"
echo "Building $TAG in $BUILD_DIR"
docker build -t $TAG "$BUILD_DIR/"
NO_PUSH=${NO_PUSH:-""}
[[ "$NO_PUSH" ]] || docker push $TAG
